version: "3.3"
services:
  portfolio-api:
    container_name: portfolio_api
    image: "${SERVER_HOST}/portfolio-api:${TAG_API:-latest}"
    networks:
      - portfolio-network
    volumes:
      - ${VOLUME_DATA_PORTFOLIO}:/data/contacts
    env_file:
      - .env.porfolio
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portfolio-api.rule=Host(`${SERVER_HOST}`) && PathPrefix(`/service`)" 
        - "traefik.http.routers.portfolio-api.middlewares=portfolio-api-stripprefix"
        - "traefik.http.middlewares.portfolio-api-stripprefix.stripprefix.prefixes=/service"
        - "traefik.http.routers.portfolio-api.entrypoints=web"
        - "traefik.http.services.portfolio-api.loadbalancer.server.port=8000"
networks:
  portfolio-network:
    external: true

